// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr4D4KkhVyDZNVr1_3tQueX-y7tnKcVQ8',
    appId: '1:603131032089:web:5665d45c536e759065f088',
    messagingSenderId: '603131032089',
    projectId: 'orderx-7e725',
    authDomain: 'orderx-7e725.firebaseapp.com',
    storageBucket: 'orderx-7e725.firebasestorage.app',
    measurementId: 'G-JS3L2349N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxpY22SdW2mQS9uTre_fIy-x0mOm1Jh04',
    appId: '1:603131032089:android:b05c3852ecb411c865f088',
    messagingSenderId: '603131032089',
    projectId: 'orderx-7e725',
    storageBucket: 'orderx-7e725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfqUB54YT9dWexWi44-_orwhWUnxWr9w',
    appId: '1:603131032089:ios:38b2aaf9aafe032965f088',
    messagingSenderId: '603131032089',
    projectId: 'orderx-7e725',
    storageBucket: 'orderx-7e725.firebasestorage.app',
    iosBundleId: 'com.example.atlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqfqUB54YT9dWexWi44-_orwhWUnxWr9w',
    appId: '1:603131032089:ios:38b2aaf9aafe032965f088',
    messagingSenderId: '603131032089',
    projectId: 'orderx-7e725',
    storageBucket: 'orderx-7e725.firebasestorage.app',
    iosBundleId: 'com.example.atlab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr4D4KkhVyDZNVr1_3tQueX-y7tnKcVQ8',
    appId: '1:603131032089:web:de1dcb97386bc81465f088',
    messagingSenderId: '603131032089',
    projectId: 'orderx-7e725',
    authDomain: 'orderx-7e725.firebaseapp.com',
    storageBucket: 'orderx-7e725.firebasestorage.app',
    measurementId: 'G-M144S2WPM6',
  );
}
